### ISSUE TITLE
Gifs speed

### ISSUE THREAD

**Issue by pepster01** [marcmerlin/FastLED_NeoMatrix#10]
Hi,
The problem I'm having is that any gifs I'm uploading to the ESP8266 controller, the all playing at the same speed, even if the animation is slow still play fast, is any way to set the speed for the gifs.
Any help will be appreciate
Thanks

**Comment by marcmerlin** [comment]
I'm not an expert on the gif decoder that I didn't write, but I do think it respects playing speed.
Try going to https://ezgif.com/optimize/ upload a gif, and use the speed icon to change the speed.
Hopefully that will work.

**Comment by pepster01** [comment]
I did try but with the same result, thanks anyway.
One more thing if you can spare few more munities, I know the brightness  is set at 32 in the config.h file but when I try to change for more brightness nothing changes any idea?
Thanks for your time.

**Comment by marcmerlin** [comment]
Sorry, then I'm not sure. You can of course slow down the speed at which you call the loop that animates the gifs, I think the decoder keeps track of time on its own, but if you don't call it very often, it can't animate more often than you call it.
Brightness can be set/reset in multiple place, you should read the code you're running and look for brighness calls, hopefully you can find it, brightness definitely works, I use it all the time.

**Comment by marcmerlin** [comment]
I don't think there is more help I can provide on this issue, so I'll close it, but if you reply I will see it and re-open if necessary

**Comment by pepster01** [comment]
I want you to know that coding is all new to me, I'm learning at the moment, I love this project that you create.
I did read all the code and config tab and I can only find brightness in two places, I did try with the find function but with the same result,  is the a command line that I have to put in the code? 
if you don't want to replay I understand, thank anyway.

**Comment by marcmerlin** [comment]
Try running matrix->setBrightness(16) in your code, hopefully that will work.

**Comment by pepster01** [comment]
YES fix it, 
thanks a lots for that, I really appreciate the help,
