### ISSUE TITLE
Random state of matrix during boot - FastLED

### ISSUE THREAD

**Issue by netmindz** [marcmerlin/FastLED_NeoMatrix#13]
When running a sketch that uses FastLED output such as APA102, there is a period where most of the LEDs are set to a random color, almost as if the CRGB array is set as uninitialized. So if I run my own startup panel that lights each LED up and then turns off, the randomness is replaced.

I simpler workaround is to use fill_solid with black, during setup, but that doesn't remove the flash of random, only leaves the matrix in a clean state ready for loop

**Comment by marcmerlin** [comment]
You didn't give your code, but assuming it looks something like this
```
#define NUMMATRIX (mw*mh)
CRGB leds[NUMMATRIX];
FastLED_NeoMatrix *matrix = new FastLED_NeoMatrix(leds, 16, 16, 2, 2, 
  NEO_MATRIX_BOTTOM     + NEO_MATRIX_RIGHT +
    NEO_MATRIX_COLUMNS + NEO_MATRIX_ZIGZAG + 
    NEO_TILE_TOP + NEO_TILE_RIGHT +  NEO_TILE_PROGRESSIVE);
```

Your array is based on the initial values stored by the leds array.  Defined as above, it should be initialized to 0's. If you use malloc it will not. In that case use calloc instead to get zero initialized.

Does that help?

**Comment by netmindz** [comment]
https://github.com/netmindz/arduino/blob/2e638996ce1c75eebb8daadfda70763951e8049e/Deevstock/DSGrid/neomatrix_config.h#L295

**Comment by marcmerlin** [comment]
I'm wrong about C arrays being initialized.
It would have to be 
```
CRGB leds[NUMMATRIX] = {};
```
But you are using my ESP32 friendly malloc at runtime (arrays at compile time take other ESP32 memory that may run out faster).
You have this in setup:
```
        matrixleds = (CRGB *) mallocordie("matrixleds", sizeof(CRGB) * NUMMATRIX, 1);
```

line 486 you have
```
mem = malloc(req);
```
Try this instead:
```
mem = calloc(1, req);
```
If that works, I'll change it on my side.

**Comment by netmindz** [comment]
yeah, that fixes it thanks @marcmerlin
