### ISSUE TITLE
Rendering high-resolution drawings on low-resolution LED matrices

### ISSUE THREAD

**Issue by rah2501** [marcmerlin/FastLED_NeoMatrix#14]
Hi there,

I have an 8x8 matrix which I'm using to display animated shapes using FastLED_NeoMatrix.  Obviously 8x8 is very low resolution.  I'm wondering if there's a(n easy) way to draw at a higher resolution and have the resulting image rendered with anti-aliasing at the resolution of the matrix?

For example, I want to draw a point at the centre of the matrix.  At the moment, if I draw a point at (MATRIX_WIDTH/2,MATRIX_HEIGHT/2), I get a single off-centre LED lit brightly.  What I'd rather have is all four LEDs around the centre point lit slightly less brightly.

Is this a problem which already has a solution?  I've looked at this library, Framebuffer_GFX and Adafruit-GFX-Library but haven't found anything helpful.  I've searched the web and found nothing useful either.

Any help would be appreciated.

Thanks,

rah

**Comment by marcmerlin** [comment]
Thanks for asking. I totally understand what you're asking for, but no, there zero code for shrinking images and doing antialiasing. If I had to do it, I would use something like gimp to pre-shrink your animation on a computer that can use better algorithms to shrink, but between you and me, don't expect the result to be good, or really usable on 8x8. Even 16x16 is really small.
you could do some pan and scroll though.
Have a look at https://marc.merlins.org/perso/arduino/post_2017-04-24_Adafruit-GFX-on-NeoMatrix-and-RGB-Matrix-Panel-Demo.html and how I handle a 24x24 bitmap on a smaller displays
and 
https://youtu.be/9yGZLtewmfI?si=K5ZZ0dAtQr67cwUm&t=179
I believe the 24x24 pixmap was actually 32x32 and I first shrunk it on my computer.

**Comment by marcmerlin** [comment]
I will close this to not forget to do so later, but feel free to reply further if you wish

**Comment by rah2501** [comment]
Thanks for your response.  To be clear, I'm drawing the shapes at runtime so can't do preprocessing unfortunately.  I suppose I'll have to try and put something together myself, nevermind.  Cheers.

**Comment by marcmerlin** [comment]
Good luck. If you're drawing yourself, hopefully you can just draw in 8x8 so that you don't have to shrink later.

**Comment by rah2501** [comment]
For those who might follow, I found some anti-aliasing code here: https://github.com/Bodmer/TFT_eSPI/blob/317ce97e598c004d158b87d01940a31acfb3eced/TFT_eSPI.cpp#L4472
