### ISSUE TITLE
How to create virtual array? 

### ISSUE THREAD

**Issue by Kamal-Sonani** [marcmerlin/FastLED_NeoMatrix#4]
right now i found (Horizontal S)
1 - 2-3-4-5 
10-9-8-7-6
11..............15
**&**
1 - 2-3-4-5
6-7-8-9-10
11..............15

i want (Vertical Z connection)

1      6     11
2      7     12
3      8     13
4      9    14
5     10    15

i wrote fixed array for that,
{
1,6	,11	,16	,21	,26	,31	,36,
2,7	,12	,17	,22	,27	,32	,37,
3,8	,13	,18	,23	,28	,33	,38,
4,9	,14	,19	,24	,29	,34	,39,
5,10 ,15   ,20    ,25   ,30   ,35   ,40
};
 but i want to know that any library have this function?

**Comment by marcmerlin** [comment]
Please read https://learn.adafruit.com/adafruit-neopixel-uberguide/neomatrix-library
you probably want
NEO_MATRIX_TOP     + NEO_MATRIX_LEFT + NEO_MATRIX_COLUMNS + NEO_MATRIX_PROGRESSIVE

**Comment by marcmerlin** [comment]
I assume this is fixed.
